{% set name = "alfasim-sdk" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/alfasim_sdk-{{ version }}.tar.gz
  sha256: 6e35061cdf1c635c4bb4e574da08cff74ff45295b70ad43cd36161f53e525474

build:
  entry_points:
    - alfasim-sdk=alfasim_sdk:console_main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42.0
    - pip
  run:
    - python >={{ python_min }}
    - python-hookman
    - typing_inspect
    - strictyaml >=1.4.3
    - boltons
    - click >=7.0
    - barril >=1.13,<3.0
    - pluggy >=0.13.0
    - h5py

test:
  imports:
    - alfasim_sdk
  commands:
    - pip check
    - alfasim-sdk --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/esss/alfasim-sdk
  summary: ALFAsim API/SDK
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cauebs
    - nicoddemus
    - prusse-martin
