{% set name = "alfasim-sdk" %}
{% set version = "0.17.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/alfasim_sdk-{{ version }}.tar.gz
  sha256: 09756989ae009c185c5c9b5e3885092b9ab3d01d49dd71e450304d88535e9c6c

build:
  entry_points:
    - alfasim-sdk=alfasim_sdk:console_main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools >=42.0
    - wheel
    - pip
  run:
    - python >=3.6
    - python-hookman
    - typing_inspect
    - strictyaml <1.4
    - ruamel.yaml <0.16.13
    - boltons
    - click >=7.0
    - barril >=1.13,<2.0
    - pluggy >=0.13.0
    - h5py

test:
  imports:
    - alfasim_sdk
  commands:
    - pip check
    - alfasim-sdk --help
  requires:
    - pip

about:
  home: https://github.com/esss/alfasim-sdk
  summary: ALFAsim API/SDK
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nicoddemus
    - prusse-martin
